services:
  - type: web
    name: mon-super-bot
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11 # Ou la version de Python que vous préférez (ex: 3.12.0)
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py # ou votre commande de démarrage
