services:
  - type: web
    name: razor-bot
    env: python
    region: frankfurt  # ou oregon / singapore (selon ta région)
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
